CREATE TABLE Employee
(
    ID                NUMBER(19)              GENERATED BY DEFAULT AS IDENTITY,
    FIRST_NAME        VARCHAR2(20 CHAR)       NOT NULL,
    LAST_NAME         VARCHAR2(20 CHAR)       NOT NULL,
    DATE_OF_BIRTH     DATE                    NOT NULL,
    COMPANY_ID        NUMBER(19)              NOT NULL,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ID)
);